# Generated by Django 4.0.3 on 2022-04-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=4000)),
                ('img_product', models.URLField()),
                ('start_bit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
