# Generated by Django 4.0.3 on 2022-05-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctions_closed_auctions_user_bids_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fashion'), (2, 'Toys'), (3, 'Eletronics'), (4, 'Home'), (5, 'Other')], default=5),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.auctions'),
        ),
    ]
